paths:
    training_images: ../data/raw/GTSRB_Final_Training_Images/GTSRB/Final_Training/Images/*/*.csv
    test_GT: ../data/raw/GTSRB_Final_Test_GT/GT-final_test.csv
    test_images: ../data/raw/GTSRB_Final_Test_Images/GTSRB/Final_Test/Images/
    save_model_path: C:/Users/Elisa SEBASTIAN/hands-on-2021/models/
    load_model_path: ../models/traffic_signs

parameters:
    IMAGE_WIDTH: 30
    IMAGE_HEIGHT: 30
    
